/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  anon_sym_COLON = 3,
  anon_sym_note = 4,
  anon_sym_query = 5,
  anon_sym_ATsession = 6,
  anon_sym_ATend = 7,
  anon_sym_ATexercise = 8,
  anon_sym_ATtemplate = 9,
  anon_sym_note_COLON = 10,
  sym_date = 11,
  anon_sym_STAR = 12,
  anon_sym_BANG = 13,
  anon_sym_W = 14,
  aux_sym_item_token1 = 15,
  aux_sym_name_token1 = 16,
  sym_weight = 17,
  sym_rep_scheme = 18,
  sym_time = 19,
  sym_distance = 20,
  sym_quoted_string = 21,
  sym_source_file = 22,
  sym__entry = 23,
  sym_singleline_entry = 24,
  sym_note_entry = 25,
  sym_query_entry = 26,
  sym_session_block = 27,
  sym_exercise_block = 28,
  sym_template_block = 29,
  sym_item_line = 30,
  sym_note_line = 31,
  sym_metadata_line = 32,
  sym_flag = 33,
  sym_item = 34,
  sym_identifier = 35,
  sym_name = 36,
  sym_text_until_newline = 37,
  sym_details = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_session_block_repeat1 = 40,
  aux_sym_exercise_block_repeat1 = 41,
  aux_sym_details_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_note] = "note",
  [anon_sym_query] = "query",
  [anon_sym_ATsession] = "@session",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATexercise] = "@exercise",
  [anon_sym_ATtemplate] = "@template",
  [anon_sym_note_COLON] = "note:",
  [sym_date] = "date",
  [anon_sym_STAR] = "*",
  [anon_sym_BANG] = "!",
  [anon_sym_W] = "W",
  [aux_sym_item_token1] = "item_token1",
  [aux_sym_name_token1] = "name_token1",
  [sym_weight] = "weight",
  [sym_rep_scheme] = "rep_scheme",
  [sym_time] = "time",
  [sym_distance] = "distance",
  [sym_quoted_string] = "quoted_string",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_singleline_entry] = "singleline_entry",
  [sym_note_entry] = "note_entry",
  [sym_query_entry] = "query_entry",
  [sym_session_block] = "session_block",
  [sym_exercise_block] = "exercise_block",
  [sym_template_block] = "template_block",
  [sym_item_line] = "item_line",
  [sym_note_line] = "note_line",
  [sym_metadata_line] = "metadata_line",
  [sym_flag] = "flag",
  [sym_item] = "item",
  [sym_identifier] = "identifier",
  [sym_name] = "name",
  [sym_text_until_newline] = "text_until_newline",
  [sym_details] = "details",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_session_block_repeat1] = "session_block_repeat1",
  [aux_sym_exercise_block_repeat1] = "exercise_block_repeat1",
  [aux_sym_details_repeat1] = "details_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_note] = anon_sym_note,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_ATsession] = anon_sym_ATsession,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATexercise] = anon_sym_ATexercise,
  [anon_sym_ATtemplate] = anon_sym_ATtemplate,
  [anon_sym_note_COLON] = anon_sym_note_COLON,
  [sym_date] = sym_date,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_W] = anon_sym_W,
  [aux_sym_item_token1] = aux_sym_item_token1,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [sym_weight] = sym_weight,
  [sym_rep_scheme] = sym_rep_scheme,
  [sym_time] = sym_time,
  [sym_distance] = sym_distance,
  [sym_quoted_string] = sym_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_singleline_entry] = sym_singleline_entry,
  [sym_note_entry] = sym_note_entry,
  [sym_query_entry] = sym_query_entry,
  [sym_session_block] = sym_session_block,
  [sym_exercise_block] = sym_exercise_block,
  [sym_template_block] = sym_template_block,
  [sym_item_line] = sym_item_line,
  [sym_note_line] = sym_note_line,
  [sym_metadata_line] = sym_metadata_line,
  [sym_flag] = sym_flag,
  [sym_item] = sym_item,
  [sym_identifier] = sym_identifier,
  [sym_name] = sym_name,
  [sym_text_until_newline] = sym_text_until_newline,
  [sym_details] = sym_details,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_session_block_repeat1] = aux_sym_session_block_repeat1,
  [aux_sym_exercise_block_repeat1] = aux_sym_exercise_block_repeat1,
  [aux_sym_details_repeat1] = aux_sym_details_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsession] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATexercise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATtemplate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_W] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_rep_scheme] = {
    .visible = true,
    .named = true,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_distance] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_singleline_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_note_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_query_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_session_block] = {
    .visible = true,
    .named = true,
  },
  [sym_exercise_block] = {
    .visible = true,
    .named = true,
  },
  [sym_template_block] = {
    .visible = true,
    .named = true,
  },
  [sym_item_line] = {
    .visible = true,
    .named = true,
  },
  [sym_note_line] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_line] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text_until_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_details] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_session_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exercise_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_details_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_date = 1,
  field_details = 2,
  field_distance = 3,
  field_flag = 4,
  field_item = 5,
  field_key = 6,
  field_name = 7,
  field_note = 8,
  field_rep_scheme = 9,
  field_sql = 10,
  field_text = 11,
  field_time = 12,
  field_value = 13,
  field_weight = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_date] = "date",
  [field_details] = "details",
  [field_distance] = "distance",
  [field_flag] = "flag",
  [field_item] = "item",
  [field_key] = "key",
  [field_name] = "name",
  [field_note] = "note",
  [field_rep_scheme] = "rep_scheme",
  [field_sql] = "sql",
  [field_text] = "text",
  [field_time] = "time",
  [field_value] = "value",
  [field_weight] = "weight",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 3},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 5},
  [11] = {.index = 19, .length = 1},
  [12] = {.index = 20, .length = 1},
  [13] = {.index = 21, .length = 4},
  [14] = {.index = 25, .length = 10},
  [15] = {.index = 35, .length = 2},
  [16] = {.index = 37, .length = 2},
  [17] = {.index = 39, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_date, 0},
    {field_text, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_date, 0},
    {field_name, 2},
    {field_sql, 3},
  [6] =
    {field_date, 0},
    {field_flag, 1},
    {field_item, 2},
  [9] =
    {field_weight, 0},
  [10] =
    {field_rep_scheme, 0},
  [11] =
    {field_time, 0},
  [12] =
    {field_distance, 0},
  [13] =
    {field_note, 0},
  [14] =
    {field_distance, 0, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_time, 0, .inherited = true},
    {field_weight, 0, .inherited = true},
  [19] =
    {field_key, 0},
  [20] =
    {field_text, 1},
  [21] =
    {field_date, 0},
    {field_details, 4},
    {field_flag, 1},
    {field_item, 2},
  [25] =
    {field_distance, 0, .inherited = true},
    {field_distance, 1, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_note, 1, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_rep_scheme, 1, .inherited = true},
    {field_time, 0, .inherited = true},
    {field_time, 1, .inherited = true},
    {field_weight, 0, .inherited = true},
    {field_weight, 1, .inherited = true},
  [35] =
    {field_key, 0},
    {field_value, 2},
  [37] =
    {field_details, 2},
    {field_item, 0},
  [39] =
    {field_date, 2},
    {field_flag, 3},
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(176);
      ADVANCE_MAP(
        '\n', 177,
        '!', 191,
        '"', 3,
        '#', 178,
        '*', 190,
        ':', 179,
        '@', 45,
        'B', 15,
        'W', 192,
        'n', 112,
        'q', 155,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(177);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(201);
      if (lookahead != 0) ADVANCE(202);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(191);
      if (lookahead == '*') ADVANCE(190);
      if (lookahead == 'W') ADVANCE(192);
      if (lookahead == 'n') ADVANCE(124);
      if (lookahead == 'q') ADVANCE(155);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(227);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '-', 174,
        '.', 166,
        '/', 167,
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'x', 168,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(175);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 166,
        '/', 167,
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'x', 168,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 166,
        '/', 167,
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'x', 168,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 166,
        '/', 167,
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'x', 168,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '.', 166,
        '/', 167,
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'x', 168,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '.', 169,
        'c', 26,
        'g', 214,
        'k', 65,
        'l', 28,
        'o', 161,
        'p', 120,
        's', 153,
        't', 213,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        '.', 173,
        'c', 27,
        'g', 210,
        'k', 67,
        'l', 30,
        'o', 162,
        'p', 122,
        's', 154,
        't', 209,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '@') ADVANCE(195);
      if (lookahead == 'n') ADVANCE(198);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 13:
      if (lookahead == '@') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 14:
      if (lookahead == 'B') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'W') ADVANCE(211);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(131);
      if (lookahead == 'e') ADVANCE(98);
      if (lookahead == 'm') ADVANCE(223);
      if (lookahead == 't') ADVANCE(204);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(129);
      if (lookahead == 'd') ADVANCE(223);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(217);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(128);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(89);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(143);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(145);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(150);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(136);
      if (lookahead == 't') ADVANCE(211);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(137);
      if (lookahead == 't') ADVANCE(203);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(211);
      END_STATE();
    case 29:
      if (lookahead == 'b') ADVANCE(204);
      END_STATE();
    case 30:
      if (lookahead == 'b') ADVANCE(203);
      END_STATE();
    case 31:
      ADVANCE_MAP(
        'c', 16,
        'd', 218,
        'f', 119,
        'g', 207,
        'h', 220,
        'i', 94,
        'k', 66,
        'l', 29,
        'm', 225,
        'n', 87,
        'o', 156,
        'p', 115,
        's', 219,
        't', 206,
        'w', 63,
        'y', 17,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(221);
      END_STATE();
    case 33:
      ADVANCE_MAP(
        'c', 26,
        'g', 214,
        'k', 65,
        'l', 28,
        'o', 161,
        'p', 120,
        's', 153,
        't', 213,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ADVANCE_MAP(
        'c', 27,
        'g', 210,
        'k', 67,
        'l', 30,
        'o', 162,
        'p', 122,
        's', 154,
        't', 209,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(75);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 'd') ADVANCE(211);
      END_STATE();
    case 40:
      if (lookahead == 'd') ADVANCE(223);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(204);
      END_STATE();
    case 42:
      if (lookahead == 'd') ADVANCE(217);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(184);
      END_STATE();
    case 44:
      if (lookahead == 'd') ADVANCE(203);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == 's') ADVANCE(47);
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(211);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(223);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(223);
      if (lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(204);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(217);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(181);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(203);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(186);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(187);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(180);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(151);
      END_STATE();
    case 65:
      if (lookahead == 'g') ADVANCE(211);
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(204);
      if (lookahead == 'i') ADVANCE(82);
      if (lookahead == 'm') ADVANCE(223);
      END_STATE();
    case 67:
      if (lookahead == 'g') ADVANCE(203);
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 68:
      if (lookahead == 'g') ADVANCE(133);
      if (lookahead == 'm') ADVANCE(64);
      END_STATE();
    case 69:
      if (lookahead == 'g') ADVANCE(134);
      END_STATE();
    case 70:
      if (lookahead == 'g') ADVANCE(135);
      END_STATE();
    case 71:
      if (lookahead == 'h') ADVANCE(223);
      END_STATE();
    case 72:
      if (lookahead == 'h') ADVANCE(217);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(223);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 75:
      if (lookahead == 'i') ADVANCE(140);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(93);
      if (lookahead == 'm') ADVANCE(204);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(91);
      if (lookahead == 'm') ADVANCE(211);
      END_STATE();
    case 78:
      if (lookahead == 'i') ADVANCE(95);
      if (lookahead == 'm') ADVANCE(203);
      END_STATE();
    case 79:
      if (lookahead == 'i') ADVANCE(118);
      END_STATE();
    case 80:
      if (lookahead == 'k') ADVANCE(217);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(113);
      END_STATE();
    case 83:
      if (lookahead == 'l') ADVANCE(114);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(125);
      END_STATE();
    case 85:
      if (lookahead == 'm') ADVANCE(211);
      END_STATE();
    case 86:
      if (lookahead == 'm') ADVANCE(204);
      END_STATE();
    case 87:
      if (lookahead == 'm') ADVANCE(73);
      END_STATE();
    case 88:
      if (lookahead == 'm') ADVANCE(126);
      END_STATE();
    case 89:
      if (lookahead == 'm') ADVANCE(203);
      END_STATE();
    case 90:
      if (lookahead == 'm') ADVANCE(64);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(211);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(43);
      if (lookahead == 'x') ADVANCE(60);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(204);
      END_STATE();
    case 94:
      if (lookahead == 'n') ADVANCE(224);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(203);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(183);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(147);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(146);
      END_STATE();
    case 102:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 103:
      if (lookahead == 'n') ADVANCE(105);
      END_STATE();
    case 104:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 105:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 106:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 107:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 109:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 110:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 112:
      if (lookahead == 'o') ADVANCE(148);
      END_STATE();
    case 113:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 114:
      if (lookahead == 'o') ADVANCE(69);
      END_STATE();
    case 115:
      if (lookahead == 'o') ADVANCE(157);
      END_STATE();
    case 116:
      if (lookahead == 'o') ADVANCE(142);
      END_STATE();
    case 117:
      if (lookahead == 'o') ADVANCE(105);
      END_STATE();
    case 118:
      if (lookahead == 'o') ADVANCE(96);
      END_STATE();
    case 119:
      if (lookahead == 'o') ADVANCE(116);
      if (lookahead == 't') ADVANCE(223);
      END_STATE();
    case 120:
      if (lookahead == 'o') ADVANCE(159);
      END_STATE();
    case 121:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 122:
      if (lookahead == 'o') ADVANCE(160);
      END_STATE();
    case 123:
      if (lookahead == 'o') ADVANCE(107);
      END_STATE();
    case 124:
      if (lookahead == 'o') ADVANCE(152);
      END_STATE();
    case 125:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 126:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 127:
      if (lookahead == 'r') ADVANCE(223);
      END_STATE();
    case 128:
      if (lookahead == 'r') ADVANCE(217);
      END_STATE();
    case 129:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 130:
      if (lookahead == 'r') ADVANCE(164);
      END_STATE();
    case 131:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 132:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 133:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 134:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 135:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 137:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 138:
      if (lookahead == 's') ADVANCE(139);
      END_STATE();
    case 139:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 140:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 141:
      if (lookahead == 't') ADVANCE(211);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(223);
      END_STATE();
    case 143:
      if (lookahead == 't') ADVANCE(204);
      END_STATE();
    case 144:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 145:
      if (lookahead == 't') ADVANCE(203);
      END_STATE();
    case 146:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 147:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 148:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 149:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 150:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 151:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 152:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 153:
      if (lookahead == 't') ADVANCE(121);
      END_STATE();
    case 154:
      if (lookahead == 't') ADVANCE(123);
      END_STATE();
    case 155:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 156:
      if (lookahead == 'u') ADVANCE(97);
      if (lookahead == 'z') ADVANCE(204);
      END_STATE();
    case 157:
      if (lookahead == 'u') ADVANCE(99);
      END_STATE();
    case 158:
      if (lookahead == 'u') ADVANCE(128);
      END_STATE();
    case 159:
      if (lookahead == 'u') ADVANCE(102);
      END_STATE();
    case 160:
      if (lookahead == 'u') ADVANCE(104);
      END_STATE();
    case 161:
      if (lookahead == 'u') ADVANCE(108);
      if (lookahead == 'z') ADVANCE(211);
      END_STATE();
    case 162:
      if (lookahead == 'u') ADVANCE(110);
      if (lookahead == 'z') ADVANCE(203);
      END_STATE();
    case 163:
      if (lookahead == 'y') ADVANCE(217);
      END_STATE();
    case 164:
      if (lookahead == 'y') ADVANCE(182);
      END_STATE();
    case 165:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(165);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 166:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 167:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(215);
      END_STATE();
    case 168:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 169:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 170:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 171:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(189);
      END_STATE();
    case 172:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 173:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 174:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(170);
      END_STATE();
    case 175:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(171);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(178);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_note);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_note);
      if (lookahead == ':') ADVANCE(188);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_ATsession);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_ATend);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_ATexercise);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_ATtemplate);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(anon_sym_note_COLON);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(anon_sym_W);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == ':') ADVANCE(188);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(200);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'd') ADVANCE(185);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(197);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(193);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'n') ADVANCE(194);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'o') ADVANCE(199);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 't') ADVANCE(196);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(200);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(202);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(202);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(103);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(205);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(172);
      if (lookahead == 'r') ADVANCE(208);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(212);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_rep_scheme);
      if (lookahead == '/') ADVANCE(167);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(215);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_rep_scheme);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == 'a') ADVANCE(163);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == 'o') ADVANCE(158);
      if (lookahead == 'r') ADVANCE(217);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == 'u') ADVANCE(149);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_distance);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'e') ADVANCE(144);
      if (lookahead == 'i') ADVANCE(226);
      if (lookahead == 'm') ADVANCE(223);
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead == 'n') ADVANCE(222);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 165},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 165},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 165},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_ATsession] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATexercise] = ACTIONS(1),
    [anon_sym_ATtemplate] = ACTIONS(1),
    [anon_sym_note_COLON] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_W] = ACTIONS(1),
    [sym_weight] = ACTIONS(1),
    [sym_rep_scheme] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
    [sym_distance] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym__entry] = STATE(2),
    [sym_singleline_entry] = STATE(2),
    [sym_note_entry] = STATE(2),
    [sym_query_entry] = STATE(2),
    [sym_session_block] = STATE(2),
    [sym_exercise_block] = STATE(2),
    [sym_template_block] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_ATsession] = ACTIONS(7),
    [anon_sym_ATexercise] = ACTIONS(9),
    [anon_sym_ATtemplate] = ACTIONS(11),
    [sym_date] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_ATsession,
    ACTIONS(9), 1,
      anon_sym_ATexercise,
    ACTIONS(11), 1,
      anon_sym_ATtemplate,
    ACTIONS(13), 1,
      sym_date,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      anon_sym_LF,
      sym_comment,
    STATE(3), 8,
      sym__entry,
      sym_singleline_entry,
      sym_note_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [30] = 7,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_ATsession,
    ACTIONS(27), 1,
      anon_sym_ATexercise,
    ACTIONS(30), 1,
      anon_sym_ATtemplate,
    ACTIONS(33), 1,
      sym_date,
    ACTIONS(21), 2,
      anon_sym_LF,
      sym_comment,
    STATE(3), 8,
      sym__entry,
      sym_singleline_entry,
      sym_note_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [60] = 8,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_time,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    STATE(17), 1,
      aux_sym_details_repeat1,
    STATE(53), 1,
      sym_details,
  [85] = 1,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [95] = 1,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [105] = 5,
    ACTIONS(52), 1,
      anon_sym_ATend,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    STATE(44), 1,
      sym_item,
    STATE(9), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [123] = 1,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [133] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(60), 1,
      anon_sym_ATend,
    STATE(44), 1,
      sym_item,
    STATE(10), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [151] = 5,
    ACTIONS(62), 1,
      anon_sym_ATend,
    ACTIONS(64), 1,
      anon_sym_note_COLON,
    ACTIONS(67), 1,
      aux_sym_item_token1,
    STATE(44), 1,
      sym_item,
    STATE(10), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [169] = 7,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_time,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    STATE(17), 1,
      aux_sym_details_repeat1,
    STATE(61), 1,
      sym_details,
  [191] = 1,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [201] = 1,
    ACTIONS(72), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [211] = 1,
    ACTIONS(74), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [221] = 1,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [231] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(78), 1,
      anon_sym_ATend,
    STATE(44), 1,
      sym_item,
    STATE(19), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [249] = 7,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_time,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    ACTIONS(80), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym_details_repeat1,
  [271] = 7,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(84), 1,
      sym_weight,
    ACTIONS(87), 1,
      sym_rep_scheme,
    ACTIONS(90), 1,
      sym_time,
    ACTIONS(93), 1,
      sym_distance,
    ACTIONS(96), 1,
      sym_quoted_string,
    STATE(18), 1,
      aux_sym_details_repeat1,
  [293] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(99), 1,
      anon_sym_ATend,
    STATE(44), 1,
      sym_item,
    STATE(10), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [311] = 1,
    ACTIONS(101), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [321] = 1,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [331] = 1,
    ACTIONS(105), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [341] = 4,
    ACTIONS(107), 1,
      anon_sym_note,
    ACTIONS(109), 1,
      anon_sym_query,
    STATE(38), 1,
      sym_flag,
    ACTIONS(111), 3,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_W,
  [356] = 2,
    ACTIONS(115), 2,
      sym_time,
      sym_distance,
    ACTIONS(113), 4,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_quoted_string,
  [367] = 2,
    ACTIONS(119), 2,
      sym_time,
      sym_distance,
    ACTIONS(117), 4,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_quoted_string,
  [378] = 2,
    ACTIONS(123), 2,
      sym_time,
      sym_distance,
    ACTIONS(121), 4,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_quoted_string,
  [389] = 2,
    ACTIONS(127), 2,
      sym_time,
      sym_distance,
    ACTIONS(125), 4,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_quoted_string,
  [400] = 2,
    ACTIONS(131), 2,
      sym_time,
      sym_distance,
    ACTIONS(129), 4,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_quoted_string,
  [411] = 4,
    ACTIONS(133), 1,
      anon_sym_ATend,
    ACTIONS(135), 1,
      aux_sym_item_token1,
    STATE(66), 1,
      sym_identifier,
    STATE(29), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [425] = 4,
    ACTIONS(138), 1,
      anon_sym_ATend,
    ACTIONS(140), 1,
      aux_sym_item_token1,
    STATE(66), 1,
      sym_identifier,
    STATE(29), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [439] = 4,
    ACTIONS(140), 1,
      aux_sym_item_token1,
    ACTIONS(142), 1,
      anon_sym_ATend,
    STATE(66), 1,
      sym_identifier,
    STATE(30), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [453] = 2,
    STATE(40), 1,
      sym_flag,
    ACTIONS(144), 3,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_W,
  [462] = 2,
    ACTIONS(148), 1,
      anon_sym_note_COLON,
    ACTIONS(146), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [470] = 3,
    ACTIONS(150), 1,
      anon_sym_LF,
    ACTIONS(152), 1,
      aux_sym_name_token1,
    STATE(58), 1,
      sym_text_until_newline,
  [480] = 2,
    ACTIONS(156), 1,
      anon_sym_note_COLON,
    ACTIONS(154), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [488] = 2,
    ACTIONS(158), 1,
      aux_sym_item_token1,
    STATE(60), 1,
      sym_identifier,
  [495] = 2,
    ACTIONS(160), 1,
      aux_sym_name_token1,
    STATE(68), 1,
      sym_name,
  [502] = 2,
    ACTIONS(162), 1,
      aux_sym_item_token1,
    STATE(62), 1,
      sym_item,
  [509] = 1,
    ACTIONS(164), 2,
      anon_sym_LF,
      anon_sym_COLON,
  [514] = 2,
    ACTIONS(160), 1,
      aux_sym_name_token1,
    STATE(49), 1,
      sym_name,
  [521] = 1,
    ACTIONS(166), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [526] = 1,
    ACTIONS(168), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [531] = 1,
    ACTIONS(170), 1,
      anon_sym_LF,
  [535] = 1,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [539] = 1,
    ACTIONS(174), 1,
      sym_quoted_string,
  [543] = 1,
    ACTIONS(176), 1,
      sym_quoted_string,
  [547] = 1,
    ACTIONS(178), 1,
      aux_sym_item_token1,
  [551] = 1,
    ACTIONS(180), 1,
      sym_date,
  [555] = 1,
    ACTIONS(182), 1,
      anon_sym_LF,
  [559] = 1,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [563] = 1,
    ACTIONS(186), 1,
      anon_sym_LF,
  [567] = 1,
    ACTIONS(188), 1,
      anon_sym_LF,
  [571] = 1,
    ACTIONS(190), 1,
      anon_sym_LF,
  [575] = 1,
    ACTIONS(192), 1,
      anon_sym_LF,
  [579] = 1,
    ACTIONS(194), 1,
      sym_quoted_string,
  [583] = 1,
    ACTIONS(196), 1,
      anon_sym_LF,
  [587] = 1,
    ACTIONS(198), 1,
      anon_sym_LF,
  [591] = 1,
    ACTIONS(200), 1,
      anon_sym_LF,
  [595] = 1,
    ACTIONS(202), 1,
      anon_sym_COLON,
  [599] = 1,
    ACTIONS(204), 1,
      anon_sym_LF,
  [603] = 1,
    ACTIONS(206), 1,
      anon_sym_LF,
  [607] = 1,
    ACTIONS(208), 1,
      anon_sym_COLON,
  [611] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [615] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [619] = 1,
    ACTIONS(214), 1,
      sym_quoted_string,
  [623] = 1,
    ACTIONS(216), 1,
      anon_sym_COLON,
  [627] = 1,
    ACTIONS(218), 1,
      anon_sym_LF,
  [631] = 1,
    ACTIONS(220), 1,
      anon_sym_LF,
  [635] = 1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [639] = 1,
    ACTIONS(224), 1,
      anon_sym_LF,
  [643] = 1,
    ACTIONS(226), 1,
      anon_sym_LF,
  [647] = 1,
    ACTIONS(178), 1,
      aux_sym_name_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 85,
  [SMALL_STATE(6)] = 95,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 123,
  [SMALL_STATE(9)] = 133,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 169,
  [SMALL_STATE(12)] = 191,
  [SMALL_STATE(13)] = 201,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 221,
  [SMALL_STATE(16)] = 231,
  [SMALL_STATE(17)] = 249,
  [SMALL_STATE(18)] = 271,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 311,
  [SMALL_STATE(21)] = 321,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 341,
  [SMALL_STATE(24)] = 356,
  [SMALL_STATE(25)] = 367,
  [SMALL_STATE(26)] = 378,
  [SMALL_STATE(27)] = 389,
  [SMALL_STATE(28)] = 400,
  [SMALL_STATE(29)] = 411,
  [SMALL_STATE(30)] = 425,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 453,
  [SMALL_STATE(33)] = 462,
  [SMALL_STATE(34)] = 470,
  [SMALL_STATE(35)] = 480,
  [SMALL_STATE(36)] = 488,
  [SMALL_STATE(37)] = 495,
  [SMALL_STATE(38)] = 502,
  [SMALL_STATE(39)] = 509,
  [SMALL_STATE(40)] = 514,
  [SMALL_STATE(41)] = 521,
  [SMALL_STATE(42)] = 526,
  [SMALL_STATE(43)] = 531,
  [SMALL_STATE(44)] = 535,
  [SMALL_STATE(45)] = 539,
  [SMALL_STATE(46)] = 543,
  [SMALL_STATE(47)] = 547,
  [SMALL_STATE(48)] = 551,
  [SMALL_STATE(49)] = 555,
  [SMALL_STATE(50)] = 559,
  [SMALL_STATE(51)] = 563,
  [SMALL_STATE(52)] = 567,
  [SMALL_STATE(53)] = 571,
  [SMALL_STATE(54)] = 575,
  [SMALL_STATE(55)] = 579,
  [SMALL_STATE(56)] = 583,
  [SMALL_STATE(57)] = 587,
  [SMALL_STATE(58)] = 591,
  [SMALL_STATE(59)] = 595,
  [SMALL_STATE(60)] = 599,
  [SMALL_STATE(61)] = 603,
  [SMALL_STATE(62)] = 607,
  [SMALL_STATE(63)] = 611,
  [SMALL_STATE(64)] = 615,
  [SMALL_STATE(65)] = 619,
  [SMALL_STATE(66)] = 623,
  [SMALL_STATE(67)] = 627,
  [SMALL_STATE(68)] = 631,
  [SMALL_STATE(69)] = 635,
  [SMALL_STATE(70)] = 639,
  [SMALL_STATE(71)] = 643,
  [SMALL_STATE(72)] = 647,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 5, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_entry, 4, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 5, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_entry, 5, 0, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 5, 0, 4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 6, 0, 13),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 6, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_details, 1, 0, 10),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14), SHIFT_REPEAT(26),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14), SHIFT_REPEAT(25),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14), SHIFT_REPEAT(27),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14), SHIFT_REPEAT(24),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 14), SHIFT_REPEAT(28),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 6, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 8, 0, 17),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 9, 0, 17),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 8),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 8),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 6),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 6),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 7),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 9),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 9),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_line, 3, 0, 12),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_line, 3, 0, 12),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_line, 4, 0, 16),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_line, 4, 0, 16),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 3, 0, 11),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 4, 0, 15),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_until_newline, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
