/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 17
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 23
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_ATinclude = 2,
  anon_sym_ATplugin = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_file_path_token1 = 5,
  sym_comment = 6,
  anon_sym_COLON = 7,
  anon_sym_note = 8,
  anon_sym_W = 9,
  anon_sym_query = 10,
  anon_sym_ATsession = 11,
  anon_sym_ATend = 12,
  anon_sym_ATexercise = 13,
  anon_sym_ATtemplate = 14,
  anon_sym_note_COLON = 15,
  sym_date = 16,
  anon_sym_STAR = 17,
  anon_sym_BANG = 18,
  aux_sym_item_token1 = 19,
  aux_sym_name_token1 = 20,
  sym_weight = 21,
  sym_rep_scheme = 22,
  sym_duration = 23,
  sym_time_of_day = 24,
  sym_distance = 25,
  sym_quoted_string = 26,
  sym_source_file = 27,
  sym__entry = 28,
  sym_include_directive = 29,
  sym_plugin_directive = 30,
  sym_file_path = 31,
  sym_singleline_entry = 32,
  sym_note_entry = 33,
  sym_weigh_in_entry = 34,
  sym_query_entry = 35,
  sym_session_block = 36,
  sym_exercise_block = 37,
  sym_template_block = 38,
  sym_item_line = 39,
  sym_note_line = 40,
  sym_metadata_line = 41,
  sym_flag = 42,
  sym_item = 43,
  sym_identifier = 44,
  sym_name = 45,
  sym_text_until_newline = 46,
  sym_details = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_session_block_repeat1 = 49,
  aux_sym_exercise_block_repeat1 = 50,
  aux_sym_details_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_ATinclude] = "@include",
  [anon_sym_ATplugin] = "@plugin",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_file_path_token1] = "file_path_token1",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_note] = "note",
  [anon_sym_W] = "W",
  [anon_sym_query] = "query",
  [anon_sym_ATsession] = "@session",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATexercise] = "@exercise",
  [anon_sym_ATtemplate] = "@template",
  [anon_sym_note_COLON] = "note:",
  [sym_date] = "date",
  [anon_sym_STAR] = "*",
  [anon_sym_BANG] = "!",
  [aux_sym_item_token1] = "item_token1",
  [aux_sym_name_token1] = "name_token1",
  [sym_weight] = "weight",
  [sym_rep_scheme] = "rep_scheme",
  [sym_duration] = "duration",
  [sym_time_of_day] = "time_of_day",
  [sym_distance] = "distance",
  [sym_quoted_string] = "quoted_string",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_include_directive] = "include_directive",
  [sym_plugin_directive] = "plugin_directive",
  [sym_file_path] = "file_path",
  [sym_singleline_entry] = "singleline_entry",
  [sym_note_entry] = "note_entry",
  [sym_weigh_in_entry] = "weigh_in_entry",
  [sym_query_entry] = "query_entry",
  [sym_session_block] = "session_block",
  [sym_exercise_block] = "exercise_block",
  [sym_template_block] = "template_block",
  [sym_item_line] = "item_line",
  [sym_note_line] = "note_line",
  [sym_metadata_line] = "metadata_line",
  [sym_flag] = "flag",
  [sym_item] = "item",
  [sym_identifier] = "identifier",
  [sym_name] = "name",
  [sym_text_until_newline] = "text_until_newline",
  [sym_details] = "details",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_session_block_repeat1] = "session_block_repeat1",
  [aux_sym_exercise_block_repeat1] = "exercise_block_repeat1",
  [aux_sym_details_repeat1] = "details_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_ATinclude] = anon_sym_ATinclude,
  [anon_sym_ATplugin] = anon_sym_ATplugin,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_file_path_token1] = aux_sym_file_path_token1,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_note] = anon_sym_note,
  [anon_sym_W] = anon_sym_W,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_ATsession] = anon_sym_ATsession,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATexercise] = anon_sym_ATexercise,
  [anon_sym_ATtemplate] = anon_sym_ATtemplate,
  [anon_sym_note_COLON] = anon_sym_note_COLON,
  [sym_date] = sym_date,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_item_token1] = aux_sym_item_token1,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [sym_weight] = sym_weight,
  [sym_rep_scheme] = sym_rep_scheme,
  [sym_duration] = sym_duration,
  [sym_time_of_day] = sym_time_of_day,
  [sym_distance] = sym_distance,
  [sym_quoted_string] = sym_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_include_directive] = sym_include_directive,
  [sym_plugin_directive] = sym_plugin_directive,
  [sym_file_path] = sym_file_path,
  [sym_singleline_entry] = sym_singleline_entry,
  [sym_note_entry] = sym_note_entry,
  [sym_weigh_in_entry] = sym_weigh_in_entry,
  [sym_query_entry] = sym_query_entry,
  [sym_session_block] = sym_session_block,
  [sym_exercise_block] = sym_exercise_block,
  [sym_template_block] = sym_template_block,
  [sym_item_line] = sym_item_line,
  [sym_note_line] = sym_note_line,
  [sym_metadata_line] = sym_metadata_line,
  [sym_flag] = sym_flag,
  [sym_item] = sym_item,
  [sym_identifier] = sym_identifier,
  [sym_name] = sym_name,
  [sym_text_until_newline] = sym_text_until_newline,
  [sym_details] = sym_details,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_session_block_repeat1] = aux_sym_session_block_repeat1,
  [aux_sym_exercise_block_repeat1] = aux_sym_exercise_block_repeat1,
  [aux_sym_details_repeat1] = aux_sym_details_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATplugin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_file_path_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_W] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsession] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATexercise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATtemplate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_rep_scheme] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_time_of_day] = {
    .visible = true,
    .named = true,
  },
  [sym_distance] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [sym_singleline_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_note_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_weigh_in_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_query_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_session_block] = {
    .visible = true,
    .named = true,
  },
  [sym_exercise_block] = {
    .visible = true,
    .named = true,
  },
  [sym_template_block] = {
    .visible = true,
    .named = true,
  },
  [sym_item_line] = {
    .visible = true,
    .named = true,
  },
  [sym_note_line] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_line] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text_until_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_details] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_session_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exercise_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_details_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_date = 1,
  field_details = 2,
  field_distance = 3,
  field_duration = 4,
  field_flag = 5,
  field_item = 6,
  field_key = 7,
  field_name = 8,
  field_note = 9,
  field_path = 10,
  field_rep_scheme = 11,
  field_scale = 12,
  field_sql = 13,
  field_text = 14,
  field_time_of_day = 15,
  field_value = 16,
  field_weight = 17,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_date] = "date",
  [field_details] = "details",
  [field_distance] = "distance",
  [field_duration] = "duration",
  [field_flag] = "flag",
  [field_item] = "item",
  [field_key] = "key",
  [field_name] = "name",
  [field_note] = "note",
  [field_path] = "path",
  [field_rep_scheme] = "rep_scheme",
  [field_scale] = "scale",
  [field_sql] = "sql",
  [field_text] = "text",
  [field_time_of_day] = "time_of_day",
  [field_value] = "value",
  [field_weight] = "weight",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 4},
  [10] = {.index = 22, .length = 1},
  [11] = {.index = 23, .length = 1},
  [12] = {.index = 24, .length = 1},
  [13] = {.index = 25, .length = 1},
  [14] = {.index = 26, .length = 1},
  [15] = {.index = 27, .length = 4},
  [16] = {.index = 31, .length = 5},
  [17] = {.index = 36, .length = 1},
  [18] = {.index = 37, .length = 1},
  [19] = {.index = 38, .length = 10},
  [20] = {.index = 48, .length = 3},
  [21] = {.index = 51, .length = 2},
  [22] = {.index = 53, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_date, 0},
    {field_text, 2},
  [3] =
    {field_date, 0},
    {field_weight, 2},
  [5] =
    {field_name, 1},
  [6] =
    {field_date, 0},
    {field_time_of_day, 3},
    {field_weight, 2},
  [9] =
    {field_date, 0},
    {field_scale, 3},
    {field_weight, 2},
  [12] =
    {field_date, 0},
    {field_name, 2},
    {field_sql, 3},
  [15] =
    {field_date, 0},
    {field_flag, 1},
    {field_item, 2},
  [18] =
    {field_date, 0},
    {field_scale, 4},
    {field_time_of_day, 3},
    {field_weight, 2},
  [22] =
    {field_weight, 0},
  [23] =
    {field_rep_scheme, 0},
  [24] =
    {field_duration, 0},
  [25] =
    {field_distance, 0},
  [26] =
    {field_note, 0},
  [27] =
    {field_date, 0},
    {field_details, 4},
    {field_flag, 1},
    {field_item, 2},
  [31] =
    {field_distance, 0, .inherited = true},
    {field_duration, 0, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_weight, 0, .inherited = true},
  [36] =
    {field_key, 0},
  [37] =
    {field_text, 1},
  [38] =
    {field_distance, 0, .inherited = true},
    {field_distance, 1, .inherited = true},
    {field_duration, 0, .inherited = true},
    {field_duration, 1, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_note, 1, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_rep_scheme, 1, .inherited = true},
    {field_weight, 0, .inherited = true},
    {field_weight, 1, .inherited = true},
  [48] =
    {field_date, 2},
    {field_flag, 3},
    {field_name, 4},
  [51] =
    {field_key, 0},
    {field_value, 2},
  [53] =
    {field_details, 2},
    {field_item, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(188);
      ADVANCE_MAP(
        '\n', 189,
        '!', 209,
        '"', 192,
        '#', 195,
        '*', 208,
        ':', 196,
        '@', 50,
        'B', 23,
        'P', 22,
        'T', 183,
        'W', 199,
        'n', 118,
        'q', 160,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(189);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(218);
      if (lookahead != 0) ADVANCE(219);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(242);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '-', 185,
        '.', 174,
        '/', 18,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'x', 175,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(186);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '.', 174,
        '/', 18,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'x', 175,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 174,
        '/', 18,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'x', 175,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 174,
        '/', 18,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'x', 175,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 174,
        '/', 18,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'x', 175,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'H') ADVANCE(235);
      if (lookahead == 'M') ADVANCE(236);
      if (lookahead == 'S') ADVANCE(234);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'S') ADVANCE(234);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        '.', 178,
        '/', 19,
        'c', 33,
        'g', 231,
        'k', 69,
        'l', 35,
        'o', 166,
        'p', 126,
        's', 157,
        't', 230,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '.', 180,
        'c', 34,
        'g', 227,
        'k', 71,
        'l', 37,
        'o', 167,
        'p', 128,
        's', 158,
        't', 226,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ADVANCE_MAP(
        '/', 19,
        'c', 24,
        'f', 125,
        'g', 224,
        'i', 101,
        'k', 70,
        'l', 36,
        'm', 240,
        'n', 93,
        'o', 165,
        'p', 121,
        's', 151,
        't', 223,
        'y', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ADVANCE_MAP(
        '/', 19,
        'c', 33,
        'g', 231,
        'k', 69,
        'l', 35,
        'o', 166,
        'p', 126,
        's', 157,
        't', 230,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(184);
      END_STATE();
    case 16:
      if (lookahead == '@') ADVANCE(212);
      if (lookahead == 'n') ADVANCE(215);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 17:
      if (lookahead == '@') ADVANCE(212);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 18:
      if (lookahead == 'B') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(232);
      END_STATE();
    case 19:
      if (lookahead == 'B') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'M') ADVANCE(236);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == 'S') ADVANCE(234);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == 'T') ADVANCE(172);
      END_STATE();
    case 23:
      if (lookahead == 'W') ADVANCE(228);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == 'e') ADVANCE(107);
      if (lookahead == 'm') ADVANCE(238);
      if (lookahead == 't') ADVANCE(221);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(136);
      if (lookahead == 'd') ADVANCE(238);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(91);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(148);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(146);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(150);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(154);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(139);
      if (lookahead == 't') ADVANCE(228);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(141);
      if (lookahead == 't') ADVANCE(220);
      END_STATE();
    case 35:
      if (lookahead == 'b') ADVANCE(228);
      END_STATE();
    case 36:
      if (lookahead == 'b') ADVANCE(221);
      END_STATE();
    case 37:
      if (lookahead == 'b') ADVANCE(220);
      END_STATE();
    case 38:
      ADVANCE_MAP(
        'c', 34,
        'g', 227,
        'k', 71,
        'l', 37,
        'o', 167,
        'p', 128,
        's', 158,
        't', 226,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(79);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 44:
      if (lookahead == 'd') ADVANCE(228);
      END_STATE();
    case 45:
      if (lookahead == 'd') ADVANCE(238);
      END_STATE();
    case 46:
      if (lookahead == 'd') ADVANCE(221);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(202);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(220);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(59);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(98);
      if (lookahead == 'i') ADVANCE(99);
      if (lookahead == 'p') ADVANCE(85);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(228);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(238);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(238);
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(221);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(198);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(220);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(190);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(204);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(205);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(168);
      if (lookahead == 'i') ADVANCE(99);
      if (lookahead == 'p') ADVANCE(85);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(197);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(137);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(133);
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(156);
      END_STATE();
    case 69:
      if (lookahead == 'g') ADVANCE(228);
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 70:
      if (lookahead == 'g') ADVANCE(221);
      if (lookahead == 'i') ADVANCE(87);
      if (lookahead == 'm') ADVANCE(238);
      END_STATE();
    case 71:
      if (lookahead == 'g') ADVANCE(220);
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 72:
      if (lookahead == 'g') ADVANCE(81);
      END_STATE();
    case 73:
      if (lookahead == 'g') ADVANCE(138);
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 74:
      if (lookahead == 'g') ADVANCE(140);
      END_STATE();
    case 75:
      if (lookahead == 'g') ADVANCE(142);
      END_STATE();
    case 76:
      if (lookahead == 'h') ADVANCE(238);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(238);
      END_STATE();
    case 78:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 79:
      if (lookahead == 'i') ADVANCE(145);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(100);
      if (lookahead == 'm') ADVANCE(221);
      END_STATE();
    case 81:
      if (lookahead == 'i') ADVANCE(103);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(97);
      if (lookahead == 'm') ADVANCE(228);
      END_STATE();
    case 83:
      if (lookahead == 'i') ADVANCE(102);
      if (lookahead == 'm') ADVANCE(220);
      END_STATE();
    case 84:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 85:
      if (lookahead == 'l') ADVANCE(159);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(119);
      END_STATE();
    case 88:
      if (lookahead == 'l') ADVANCE(161);
      END_STATE();
    case 89:
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 90:
      if (lookahead == 'l') ADVANCE(131);
      END_STATE();
    case 91:
      if (lookahead == 'm') ADVANCE(228);
      END_STATE();
    case 92:
      if (lookahead == 'm') ADVANCE(221);
      END_STATE();
    case 93:
      if (lookahead == 'm') ADVANCE(77);
      END_STATE();
    case 94:
      if (lookahead == 'm') ADVANCE(132);
      END_STATE();
    case 95:
      if (lookahead == 'm') ADVANCE(220);
      END_STATE();
    case 96:
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(228);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(47);
      if (lookahead == 'x') ADVANCE(65);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(221);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(239);
      END_STATE();
    case 102:
      if (lookahead == 'n') ADVANCE(220);
      END_STATE();
    case 103:
      if (lookahead == 'n') ADVANCE(191);
      END_STATE();
    case 104:
      if (lookahead == 'n') ADVANCE(201);
      END_STATE();
    case 105:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 106:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 107:
      if (lookahead == 'n') ADVANCE(152);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 109:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 110:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 112:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 113:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 114:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 115:
      if (lookahead == 'n') ADVANCE(112);
      END_STATE();
    case 116:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 117:
      if (lookahead == 'n') ADVANCE(113);
      END_STATE();
    case 118:
      if (lookahead == 'o') ADVANCE(153);
      END_STATE();
    case 119:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 120:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 121:
      if (lookahead == 'o') ADVANCE(162);
      END_STATE();
    case 122:
      if (lookahead == 'o') ADVANCE(147);
      END_STATE();
    case 123:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 124:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 125:
      if (lookahead == 'o') ADVANCE(122);
      if (lookahead == 't') ADVANCE(238);
      END_STATE();
    case 126:
      if (lookahead == 'o') ADVANCE(163);
      END_STATE();
    case 127:
      if (lookahead == 'o') ADVANCE(112);
      END_STATE();
    case 128:
      if (lookahead == 'o') ADVANCE(164);
      END_STATE();
    case 129:
      if (lookahead == 'o') ADVANCE(113);
      END_STATE();
    case 130:
      if (lookahead == 'o') ADVANCE(155);
      END_STATE();
    case 131:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 132:
      if (lookahead == 'p') ADVANCE(86);
      END_STATE();
    case 133:
      if (lookahead == 'r') ADVANCE(238);
      END_STATE();
    case 134:
      if (lookahead == 'r') ADVANCE(169);
      END_STATE();
    case 135:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 137:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 138:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 139:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 140:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 141:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 142:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 143:
      if (lookahead == 's') ADVANCE(144);
      END_STATE();
    case 144:
      if (lookahead == 's') ADVANCE(84);
      END_STATE();
    case 145:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 146:
      if (lookahead == 't') ADVANCE(228);
      END_STATE();
    case 147:
      if (lookahead == 't') ADVANCE(238);
      END_STATE();
    case 148:
      if (lookahead == 't') ADVANCE(221);
      END_STATE();
    case 149:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 150:
      if (lookahead == 't') ADVANCE(220);
      END_STATE();
    case 151:
      if (lookahead == 't') ADVANCE(123);
      END_STATE();
    case 152:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 153:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 154:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 155:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 156:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 157:
      if (lookahead == 't') ADVANCE(127);
      END_STATE();
    case 158:
      if (lookahead == 't') ADVANCE(129);
      END_STATE();
    case 159:
      if (lookahead == 'u') ADVANCE(72);
      END_STATE();
    case 160:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 161:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 162:
      if (lookahead == 'u') ADVANCE(106);
      END_STATE();
    case 163:
      if (lookahead == 'u') ADVANCE(108);
      END_STATE();
    case 164:
      if (lookahead == 'u') ADVANCE(110);
      END_STATE();
    case 165:
      if (lookahead == 'u') ADVANCE(105);
      if (lookahead == 'z') ADVANCE(221);
      END_STATE();
    case 166:
      if (lookahead == 'u') ADVANCE(114);
      if (lookahead == 'z') ADVANCE(228);
      END_STATE();
    case 167:
      if (lookahead == 'u') ADVANCE(116);
      if (lookahead == 'z') ADVANCE(220);
      END_STATE();
    case 168:
      if (lookahead == 'x') ADVANCE(65);
      END_STATE();
    case 169:
      if (lookahead == 'y') ADVANCE(200);
      END_STATE();
    case 170:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(170);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 171:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(194);
      END_STATE();
    case 172:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 173:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 174:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 175:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(233);
      END_STATE();
    case 176:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 177:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 178:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 179:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(237);
      END_STATE();
    case 180:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 181:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 182:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(207);
      END_STATE();
    case 183:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(173);
      END_STATE();
    case 184:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(179);
      END_STATE();
    case 185:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(181);
      END_STATE();
    case 186:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(182);
      END_STATE();
    case 187:
      if (eof) ADVANCE(188);
      ADVANCE_MAP(
        '\n', 189,
        '!', 209,
        '"', 2,
        '#', 195,
        '*', 208,
        '@', 62,
        'B', 23,
        'P', 22,
        'T', 183,
        'W', 199,
        'n', 130,
        'q', 160,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(187);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_ATinclude);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_ATplugin);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(aux_sym_file_path_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(194);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(aux_sym_file_path_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(194);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_note);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_note);
      if (lookahead == ':') ADVANCE(206);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(anon_sym_W);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_ATsession);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_ATend);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_ATexercise);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_ATtemplate);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_note_COLON);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == ':') ADVANCE(206);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(217);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'd') ADVANCE(203);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(214);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(210);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'n') ADVANCE(211);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'o') ADVANCE(216);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 't') ADVANCE(213);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(217);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(218);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(219);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(219);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == '/') ADVANCE(19);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(222);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == 'o') ADVANCE(117);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(176);
      if (lookahead == 'r') ADVANCE(225);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(19);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(82);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(115);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(229);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_rep_scheme);
      ADVANCE_MAP(
        '.', 178,
        '/', 18,
        'c', 33,
        'g', 231,
        'k', 69,
        'l', 35,
        'o', 166,
        'p', 126,
        's', 157,
        't', 230,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(232);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_rep_scheme);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(233);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_time_of_day);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_distance);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'c') ADVANCE(76);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'e') ADVANCE(149);
      if (lookahead == 'i') ADVANCE(241);
      if (lookahead == 'm') ADVANCE(238);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 187},
  [5] = {.lex_state = 187},
  [6] = {.lex_state = 187},
  [7] = {.lex_state = 187},
  [8] = {.lex_state = 187},
  [9] = {.lex_state = 187},
  [10] = {.lex_state = 187},
  [11] = {.lex_state = 187},
  [12] = {.lex_state = 187},
  [13] = {.lex_state = 187},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 187},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 187},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 170},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 17},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 170},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 187},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 187},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 170},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 187},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 187},
  [85] = {.lex_state = 171},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_ATinclude] = ACTIONS(1),
    [anon_sym_ATplugin] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [anon_sym_W] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_ATsession] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATexercise] = ACTIONS(1),
    [anon_sym_ATtemplate] = ACTIONS(1),
    [anon_sym_note_COLON] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_weight] = ACTIONS(1),
    [sym_rep_scheme] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_time_of_day] = ACTIONS(1),
    [sym_distance] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym__entry] = STATE(3),
    [sym_include_directive] = STATE(3),
    [sym_plugin_directive] = STATE(3),
    [sym_singleline_entry] = STATE(3),
    [sym_note_entry] = STATE(3),
    [sym_weigh_in_entry] = STATE(3),
    [sym_query_entry] = STATE(3),
    [sym_session_block] = STATE(3),
    [sym_exercise_block] = STATE(3),
    [sym_template_block] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_ATinclude] = ACTIONS(7),
    [anon_sym_ATplugin] = ACTIONS(9),
    [sym_comment] = ACTIONS(5),
    [anon_sym_ATsession] = ACTIONS(11),
    [anon_sym_ATexercise] = ACTIONS(13),
    [anon_sym_ATtemplate] = ACTIONS(15),
    [sym_date] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_ATinclude,
    ACTIONS(27), 1,
      anon_sym_ATplugin,
    ACTIONS(30), 1,
      anon_sym_ATsession,
    ACTIONS(33), 1,
      anon_sym_ATexercise,
    ACTIONS(36), 1,
      anon_sym_ATtemplate,
    ACTIONS(39), 1,
      sym_date,
    ACTIONS(21), 2,
      anon_sym_LF,
      sym_comment,
    STATE(2), 11,
      sym__entry,
      sym_include_directive,
      sym_plugin_directive,
      sym_singleline_entry,
      sym_note_entry,
      sym_weigh_in_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [39] = 9,
    ACTIONS(7), 1,
      anon_sym_ATinclude,
    ACTIONS(9), 1,
      anon_sym_ATplugin,
    ACTIONS(11), 1,
      anon_sym_ATsession,
    ACTIONS(13), 1,
      anon_sym_ATexercise,
    ACTIONS(15), 1,
      anon_sym_ATtemplate,
    ACTIONS(17), 1,
      sym_date,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 2,
      anon_sym_LF,
      sym_comment,
    STATE(2), 11,
      sym__entry,
      sym_include_directive,
      sym_plugin_directive,
      sym_singleline_entry,
      sym_note_entry,
      sym_weigh_in_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [78] = 9,
    ACTIONS(48), 1,
      anon_sym_LF,
    ACTIONS(50), 1,
      sym_weight,
    ACTIONS(52), 1,
      sym_rep_scheme,
    ACTIONS(54), 1,
      sym_duration,
    ACTIONS(56), 1,
      sym_distance,
    ACTIONS(58), 1,
      sym_quoted_string,
    STATE(6), 1,
      aux_sym_details_repeat1,
    STATE(32), 1,
      sym_details,
    ACTIONS(46), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [113] = 7,
    ACTIONS(62), 1,
      sym_weight,
    ACTIONS(65), 1,
      sym_rep_scheme,
    ACTIONS(68), 1,
      sym_duration,
    ACTIONS(71), 1,
      sym_distance,
    ACTIONS(74), 1,
      sym_quoted_string,
    STATE(5), 1,
      aux_sym_details_repeat1,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [143] = 7,
    ACTIONS(50), 1,
      sym_weight,
    ACTIONS(52), 1,
      sym_rep_scheme,
    ACTIONS(54), 1,
      sym_duration,
    ACTIONS(56), 1,
      sym_distance,
    ACTIONS(58), 1,
      sym_quoted_string,
    STATE(5), 1,
      aux_sym_details_repeat1,
    ACTIONS(77), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [173] = 2,
    ACTIONS(81), 1,
      sym_rep_scheme,
    ACTIONS(79), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
      sym_weight,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [192] = 2,
    ACTIONS(85), 1,
      sym_rep_scheme,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
      sym_weight,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [211] = 2,
    ACTIONS(89), 1,
      sym_rep_scheme,
    ACTIONS(87), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
      sym_weight,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [230] = 2,
    ACTIONS(93), 1,
      sym_rep_scheme,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
      sym_weight,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [249] = 2,
    ACTIONS(97), 1,
      sym_rep_scheme,
    ACTIONS(95), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
      sym_weight,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [268] = 4,
    ACTIONS(101), 1,
      anon_sym_LF,
    ACTIONS(103), 1,
      sym_time_of_day,
    ACTIONS(105), 1,
      sym_quoted_string,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [288] = 3,
    ACTIONS(109), 1,
      anon_sym_LF,
    ACTIONS(111), 1,
      sym_quoted_string,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [305] = 1,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [317] = 2,
    ACTIONS(117), 1,
      anon_sym_LF,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [331] = 2,
    ACTIONS(121), 1,
      anon_sym_LF,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [345] = 1,
    ACTIONS(123), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [357] = 1,
    ACTIONS(125), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [369] = 2,
    ACTIONS(127), 1,
      anon_sym_LF,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [383] = 1,
    ACTIONS(129), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [395] = 2,
    ACTIONS(131), 1,
      anon_sym_LF,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [409] = 1,
    ACTIONS(133), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [421] = 2,
    ACTIONS(137), 1,
      anon_sym_LF,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [435] = 1,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [447] = 1,
    ACTIONS(141), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [459] = 1,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [471] = 1,
    ACTIONS(145), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [483] = 2,
    ACTIONS(149), 1,
      anon_sym_LF,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [497] = 2,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [511] = 1,
    ACTIONS(155), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [523] = 2,
    ACTIONS(159), 1,
      anon_sym_LF,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [537] = 2,
    ACTIONS(163), 1,
      anon_sym_LF,
    ACTIONS(161), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [551] = 2,
    ACTIONS(167), 1,
      anon_sym_LF,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [565] = 1,
    ACTIONS(169), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [577] = 1,
    ACTIONS(171), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [589] = 1,
    ACTIONS(173), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [601] = 1,
    ACTIONS(175), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [613] = 1,
    ACTIONS(177), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [625] = 2,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [639] = 2,
    ACTIONS(185), 1,
      anon_sym_LF,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [653] = 1,
    ACTIONS(187), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [665] = 2,
    ACTIONS(189), 1,
      anon_sym_LF,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [679] = 1,
    ACTIONS(191), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_ATinclude,
      anon_sym_ATplugin,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [691] = 5,
    ACTIONS(193), 1,
      anon_sym_ATend,
    ACTIONS(195), 1,
      anon_sym_note_COLON,
    ACTIONS(197), 1,
      aux_sym_item_token1,
    STATE(87), 1,
      sym_item,
    STATE(49), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [709] = 5,
    ACTIONS(195), 1,
      anon_sym_note_COLON,
    ACTIONS(197), 1,
      aux_sym_item_token1,
    ACTIONS(199), 1,
      anon_sym_ATend,
    STATE(87), 1,
      sym_item,
    STATE(49), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [727] = 5,
    ACTIONS(195), 1,
      anon_sym_note_COLON,
    ACTIONS(197), 1,
      aux_sym_item_token1,
    ACTIONS(201), 1,
      anon_sym_ATend,
    STATE(87), 1,
      sym_item,
    STATE(45), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [745] = 5,
    ACTIONS(195), 1,
      anon_sym_note_COLON,
    ACTIONS(197), 1,
      aux_sym_item_token1,
    ACTIONS(203), 1,
      anon_sym_ATend,
    STATE(87), 1,
      sym_item,
    STATE(44), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [763] = 7,
    ACTIONS(50), 1,
      sym_weight,
    ACTIONS(52), 1,
      sym_rep_scheme,
    ACTIONS(54), 1,
      sym_duration,
    ACTIONS(56), 1,
      sym_distance,
    ACTIONS(58), 1,
      sym_quoted_string,
    STATE(6), 1,
      aux_sym_details_repeat1,
    STATE(83), 1,
      sym_details,
  [785] = 5,
    ACTIONS(205), 1,
      anon_sym_ATend,
    ACTIONS(207), 1,
      anon_sym_note_COLON,
    ACTIONS(210), 1,
      aux_sym_item_token1,
    STATE(87), 1,
      sym_item,
    STATE(49), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [803] = 5,
    ACTIONS(213), 1,
      anon_sym_note,
    ACTIONS(215), 1,
      anon_sym_W,
    ACTIONS(217), 1,
      anon_sym_query,
    STATE(66), 1,
      sym_flag,
    ACTIONS(219), 2,
      anon_sym_STAR,
      anon_sym_BANG,
  [820] = 4,
    ACTIONS(221), 1,
      anon_sym_ATend,
    ACTIONS(223), 1,
      aux_sym_item_token1,
    STATE(81), 1,
      sym_identifier,
    STATE(51), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [834] = 4,
    ACTIONS(226), 1,
      anon_sym_ATend,
    ACTIONS(228), 1,
      aux_sym_item_token1,
    STATE(81), 1,
      sym_identifier,
    STATE(53), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [848] = 4,
    ACTIONS(228), 1,
      aux_sym_item_token1,
    ACTIONS(230), 1,
      anon_sym_ATend,
    STATE(81), 1,
      sym_identifier,
    STATE(51), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [862] = 3,
    ACTIONS(232), 1,
      anon_sym_LF,
    ACTIONS(234), 1,
      aux_sym_name_token1,
    STATE(79), 1,
      sym_text_until_newline,
  [872] = 2,
    ACTIONS(238), 1,
      anon_sym_note_COLON,
    ACTIONS(236), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [880] = 2,
    STATE(63), 1,
      sym_flag,
    ACTIONS(240), 2,
      anon_sym_STAR,
      anon_sym_BANG,
  [888] = 2,
    ACTIONS(244), 1,
      anon_sym_note_COLON,
    ACTIONS(242), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [896] = 2,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_file_path,
  [903] = 2,
    ACTIONS(248), 1,
      aux_sym_item_token1,
    STATE(67), 1,
      sym_identifier,
  [910] = 2,
    ACTIONS(250), 1,
      aux_sym_name_token1,
    STATE(71), 1,
      sym_name,
  [917] = 2,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_file_path,
  [924] = 1,
    ACTIONS(252), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [929] = 2,
    ACTIONS(250), 1,
      aux_sym_name_token1,
    STATE(88), 1,
      sym_name,
  [936] = 1,
    ACTIONS(254), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [941] = 1,
    ACTIONS(256), 2,
      anon_sym_LF,
      anon_sym_COLON,
  [946] = 2,
    ACTIONS(258), 1,
      aux_sym_item_token1,
    STATE(76), 1,
      sym_item,
  [953] = 1,
    ACTIONS(260), 1,
      anon_sym_LF,
  [957] = 1,
    ACTIONS(262), 1,
      sym_weight,
  [961] = 1,
    ACTIONS(264), 1,
      anon_sym_LF,
  [965] = 1,
    ACTIONS(266), 1,
      sym_quoted_string,
  [969] = 1,
    ACTIONS(268), 1,
      anon_sym_LF,
  [973] = 1,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
  [977] = 1,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
  [981] = 1,
    ACTIONS(274), 1,
      sym_quoted_string,
  [985] = 1,
    ACTIONS(276), 1,
      anon_sym_COLON,
  [989] = 1,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [993] = 1,
    ACTIONS(280), 1,
      aux_sym_item_token1,
  [997] = 1,
    ACTIONS(282), 1,
      anon_sym_LF,
  [1001] = 1,
    ACTIONS(284), 1,
      anon_sym_LF,
  [1005] = 1,
    ACTIONS(286), 1,
      anon_sym_LF,
  [1009] = 1,
    ACTIONS(288), 1,
      anon_sym_COLON,
  [1013] = 1,
    ACTIONS(290), 1,
      sym_quoted_string,
  [1017] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [1021] = 1,
    ACTIONS(294), 1,
      sym_quoted_string,
  [1025] = 1,
    ACTIONS(296), 1,
      aux_sym_file_path_token1,
  [1029] = 1,
    ACTIONS(298), 1,
      anon_sym_LF,
  [1033] = 1,
    ACTIONS(300), 1,
      anon_sym_COLON,
  [1037] = 1,
    ACTIONS(302), 1,
      anon_sym_LF,
  [1041] = 1,
    ACTIONS(304), 1,
      sym_date,
  [1045] = 1,
    ACTIONS(280), 1,
      aux_sym_name_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 113,
  [SMALL_STATE(6)] = 143,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 211,
  [SMALL_STATE(10)] = 230,
  [SMALL_STATE(11)] = 249,
  [SMALL_STATE(12)] = 268,
  [SMALL_STATE(13)] = 288,
  [SMALL_STATE(14)] = 305,
  [SMALL_STATE(15)] = 317,
  [SMALL_STATE(16)] = 331,
  [SMALL_STATE(17)] = 345,
  [SMALL_STATE(18)] = 357,
  [SMALL_STATE(19)] = 369,
  [SMALL_STATE(20)] = 383,
  [SMALL_STATE(21)] = 395,
  [SMALL_STATE(22)] = 409,
  [SMALL_STATE(23)] = 421,
  [SMALL_STATE(24)] = 435,
  [SMALL_STATE(25)] = 447,
  [SMALL_STATE(26)] = 459,
  [SMALL_STATE(27)] = 471,
  [SMALL_STATE(28)] = 483,
  [SMALL_STATE(29)] = 497,
  [SMALL_STATE(30)] = 511,
  [SMALL_STATE(31)] = 523,
  [SMALL_STATE(32)] = 537,
  [SMALL_STATE(33)] = 551,
  [SMALL_STATE(34)] = 565,
  [SMALL_STATE(35)] = 577,
  [SMALL_STATE(36)] = 589,
  [SMALL_STATE(37)] = 601,
  [SMALL_STATE(38)] = 613,
  [SMALL_STATE(39)] = 625,
  [SMALL_STATE(40)] = 639,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 665,
  [SMALL_STATE(43)] = 679,
  [SMALL_STATE(44)] = 691,
  [SMALL_STATE(45)] = 709,
  [SMALL_STATE(46)] = 727,
  [SMALL_STATE(47)] = 745,
  [SMALL_STATE(48)] = 763,
  [SMALL_STATE(49)] = 785,
  [SMALL_STATE(50)] = 803,
  [SMALL_STATE(51)] = 820,
  [SMALL_STATE(52)] = 834,
  [SMALL_STATE(53)] = 848,
  [SMALL_STATE(54)] = 862,
  [SMALL_STATE(55)] = 872,
  [SMALL_STATE(56)] = 880,
  [SMALL_STATE(57)] = 888,
  [SMALL_STATE(58)] = 896,
  [SMALL_STATE(59)] = 903,
  [SMALL_STATE(60)] = 910,
  [SMALL_STATE(61)] = 917,
  [SMALL_STATE(62)] = 924,
  [SMALL_STATE(63)] = 929,
  [SMALL_STATE(64)] = 936,
  [SMALL_STATE(65)] = 941,
  [SMALL_STATE(66)] = 946,
  [SMALL_STATE(67)] = 953,
  [SMALL_STATE(68)] = 957,
  [SMALL_STATE(69)] = 961,
  [SMALL_STATE(70)] = 965,
  [SMALL_STATE(71)] = 969,
  [SMALL_STATE(72)] = 973,
  [SMALL_STATE(73)] = 977,
  [SMALL_STATE(74)] = 981,
  [SMALL_STATE(75)] = 985,
  [SMALL_STATE(76)] = 989,
  [SMALL_STATE(77)] = 993,
  [SMALL_STATE(78)] = 997,
  [SMALL_STATE(79)] = 1001,
  [SMALL_STATE(80)] = 1005,
  [SMALL_STATE(81)] = 1009,
  [SMALL_STATE(82)] = 1013,
  [SMALL_STATE(83)] = 1017,
  [SMALL_STATE(84)] = 1021,
  [SMALL_STATE(85)] = 1025,
  [SMALL_STATE(86)] = 1029,
  [SMALL_STATE(87)] = 1033,
  [SMALL_STATE(88)] = 1037,
  [SMALL_STATE(89)] = 1041,
  [SMALL_STATE(90)] = 1045,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 4, 0, 8),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19), SHIFT_REPEAT(11),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19), SHIFT_REPEAT(9),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19), SHIFT_REPEAT(10),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 19), SHIFT_REPEAT(8),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_details, 1, 0, 16),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 11),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 14),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 12),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 13),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 13),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 10),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_details_repeat1, 1, 0, 10),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 3, 0, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 4, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 6, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 4, 0, 6),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_entry, 4, 0, 7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 5, 0, 4),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 5, 0, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 5, 0, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 5, 0, 9),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 5, 0, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_entry, 5, 0, 7),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 5, 0, 8),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_directive, 3, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_entry, 3, 0, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_directive, 2, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_path, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 4, 0, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 5, 0, 15),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 4, 0, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 6, 0, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_entry, 4, 0, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 6, 0, 9),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 6, 0, 15),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 4, 0, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 7, 0, 20),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 8, 0, 20),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 9, 0, 20),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_line, 3, 0, 18),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_line, 3, 0, 18),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_line, 4, 0, 22),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_line, 4, 0, 22),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 3, 0, 17),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 4, 0, 21),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [270] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_until_newline, 1, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
