/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  anon_sym_COLON = 3,
  anon_sym_note = 4,
  anon_sym_W = 5,
  anon_sym_query = 6,
  anon_sym_ATsession = 7,
  anon_sym_ATend = 8,
  anon_sym_ATexercise = 9,
  anon_sym_ATtemplate = 10,
  anon_sym_note_COLON = 11,
  sym_date = 12,
  anon_sym_STAR = 13,
  anon_sym_BANG = 14,
  aux_sym_item_token1 = 15,
  aux_sym_name_token1 = 16,
  sym_weight = 17,
  sym_rep_scheme = 18,
  sym_duration = 19,
  sym_time_of_day = 20,
  sym_distance = 21,
  sym_quoted_string = 22,
  sym_source_file = 23,
  sym__entry = 24,
  sym_singleline_entry = 25,
  sym_note_entry = 26,
  sym_weigh_in_entry = 27,
  sym_query_entry = 28,
  sym_session_block = 29,
  sym_exercise_block = 30,
  sym_template_block = 31,
  sym_item_line = 32,
  sym_note_line = 33,
  sym_metadata_line = 34,
  sym_flag = 35,
  sym_item = 36,
  sym_identifier = 37,
  sym_name = 38,
  sym_text_until_newline = 39,
  sym_details = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_session_block_repeat1 = 42,
  aux_sym_exercise_block_repeat1 = 43,
  aux_sym_details_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_note] = "note",
  [anon_sym_W] = "W",
  [anon_sym_query] = "query",
  [anon_sym_ATsession] = "@session",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATexercise] = "@exercise",
  [anon_sym_ATtemplate] = "@template",
  [anon_sym_note_COLON] = "note:",
  [sym_date] = "date",
  [anon_sym_STAR] = "*",
  [anon_sym_BANG] = "!",
  [aux_sym_item_token1] = "item_token1",
  [aux_sym_name_token1] = "name_token1",
  [sym_weight] = "weight",
  [sym_rep_scheme] = "rep_scheme",
  [sym_duration] = "duration",
  [sym_time_of_day] = "time_of_day",
  [sym_distance] = "distance",
  [sym_quoted_string] = "quoted_string",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_singleline_entry] = "singleline_entry",
  [sym_note_entry] = "note_entry",
  [sym_weigh_in_entry] = "weigh_in_entry",
  [sym_query_entry] = "query_entry",
  [sym_session_block] = "session_block",
  [sym_exercise_block] = "exercise_block",
  [sym_template_block] = "template_block",
  [sym_item_line] = "item_line",
  [sym_note_line] = "note_line",
  [sym_metadata_line] = "metadata_line",
  [sym_flag] = "flag",
  [sym_item] = "item",
  [sym_identifier] = "identifier",
  [sym_name] = "name",
  [sym_text_until_newline] = "text_until_newline",
  [sym_details] = "details",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_session_block_repeat1] = "session_block_repeat1",
  [aux_sym_exercise_block_repeat1] = "exercise_block_repeat1",
  [aux_sym_details_repeat1] = "details_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_note] = anon_sym_note,
  [anon_sym_W] = anon_sym_W,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_ATsession] = anon_sym_ATsession,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATexercise] = anon_sym_ATexercise,
  [anon_sym_ATtemplate] = anon_sym_ATtemplate,
  [anon_sym_note_COLON] = anon_sym_note_COLON,
  [sym_date] = sym_date,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_item_token1] = aux_sym_item_token1,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [sym_weight] = sym_weight,
  [sym_rep_scheme] = sym_rep_scheme,
  [sym_duration] = sym_duration,
  [sym_time_of_day] = sym_time_of_day,
  [sym_distance] = sym_distance,
  [sym_quoted_string] = sym_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_singleline_entry] = sym_singleline_entry,
  [sym_note_entry] = sym_note_entry,
  [sym_weigh_in_entry] = sym_weigh_in_entry,
  [sym_query_entry] = sym_query_entry,
  [sym_session_block] = sym_session_block,
  [sym_exercise_block] = sym_exercise_block,
  [sym_template_block] = sym_template_block,
  [sym_item_line] = sym_item_line,
  [sym_note_line] = sym_note_line,
  [sym_metadata_line] = sym_metadata_line,
  [sym_flag] = sym_flag,
  [sym_item] = sym_item,
  [sym_identifier] = sym_identifier,
  [sym_name] = sym_name,
  [sym_text_until_newline] = sym_text_until_newline,
  [sym_details] = sym_details,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_session_block_repeat1] = aux_sym_session_block_repeat1,
  [aux_sym_exercise_block_repeat1] = aux_sym_exercise_block_repeat1,
  [aux_sym_details_repeat1] = aux_sym_details_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_W] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsession] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATexercise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATtemplate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_rep_scheme] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_time_of_day] = {
    .visible = true,
    .named = true,
  },
  [sym_distance] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_singleline_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_note_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_weigh_in_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_query_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_session_block] = {
    .visible = true,
    .named = true,
  },
  [sym_exercise_block] = {
    .visible = true,
    .named = true,
  },
  [sym_template_block] = {
    .visible = true,
    .named = true,
  },
  [sym_item_line] = {
    .visible = true,
    .named = true,
  },
  [sym_note_line] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_line] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text_until_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_details] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_session_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exercise_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_details_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_date = 1,
  field_details = 2,
  field_distance = 3,
  field_duration = 4,
  field_flag = 5,
  field_item = 6,
  field_key = 7,
  field_name = 8,
  field_note = 9,
  field_rep_scheme = 10,
  field_scale = 11,
  field_sql = 12,
  field_text = 13,
  field_time_of_day = 14,
  field_value = 15,
  field_weight = 16,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_date] = "date",
  [field_details] = "details",
  [field_distance] = "distance",
  [field_duration] = "duration",
  [field_flag] = "flag",
  [field_item] = "item",
  [field_key] = "key",
  [field_name] = "name",
  [field_note] = "note",
  [field_rep_scheme] = "rep_scheme",
  [field_scale] = "scale",
  [field_sql] = "sql",
  [field_text] = "text",
  [field_time_of_day] = "time_of_day",
  [field_value] = "value",
  [field_weight] = "weight",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 3},
  [7] = {.index = 14, .length = 3},
  [8] = {.index = 17, .length = 1},
  [9] = {.index = 18, .length = 1},
  [10] = {.index = 19, .length = 1},
  [11] = {.index = 20, .length = 1},
  [12] = {.index = 21, .length = 1},
  [13] = {.index = 22, .length = 5},
  [14] = {.index = 27, .length = 1},
  [15] = {.index = 28, .length = 1},
  [16] = {.index = 29, .length = 4},
  [17] = {.index = 33, .length = 4},
  [18] = {.index = 37, .length = 10},
  [19] = {.index = 47, .length = 2},
  [20] = {.index = 49, .length = 2},
  [21] = {.index = 51, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_date, 0},
    {field_text, 2},
  [2] =
    {field_date, 0},
    {field_weight, 2},
  [4] =
    {field_name, 1},
  [5] =
    {field_date, 0},
    {field_time_of_day, 3},
    {field_weight, 2},
  [8] =
    {field_date, 0},
    {field_scale, 3},
    {field_weight, 2},
  [11] =
    {field_date, 0},
    {field_name, 2},
    {field_sql, 3},
  [14] =
    {field_date, 0},
    {field_flag, 1},
    {field_item, 2},
  [17] =
    {field_weight, 0},
  [18] =
    {field_rep_scheme, 0},
  [19] =
    {field_duration, 0},
  [20] =
    {field_distance, 0},
  [21] =
    {field_note, 0},
  [22] =
    {field_distance, 0, .inherited = true},
    {field_duration, 0, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_weight, 0, .inherited = true},
  [27] =
    {field_key, 0},
  [28] =
    {field_text, 1},
  [29] =
    {field_date, 0},
    {field_scale, 4},
    {field_time_of_day, 3},
    {field_weight, 2},
  [33] =
    {field_date, 0},
    {field_details, 4},
    {field_flag, 1},
    {field_item, 2},
  [37] =
    {field_distance, 0, .inherited = true},
    {field_distance, 1, .inherited = true},
    {field_duration, 0, .inherited = true},
    {field_duration, 1, .inherited = true},
    {field_note, 0, .inherited = true},
    {field_note, 1, .inherited = true},
    {field_rep_scheme, 0, .inherited = true},
    {field_rep_scheme, 1, .inherited = true},
    {field_weight, 0, .inherited = true},
    {field_weight, 1, .inherited = true},
  [47] =
    {field_key, 0},
    {field_value, 2},
  [49] =
    {field_details, 2},
    {field_item, 0},
  [51] =
    {field_date, 2},
    {field_flag, 3},
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(174);
      ADVANCE_MAP(
        '\n', 175,
        '!', 190,
        '"', 3,
        '#', 176,
        '*', 189,
        ':', 177,
        '@', 48,
        'B', 21,
        'P', 20,
        'T', 170,
        'W', 180,
        'n', 108,
        'q', 149,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(175);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(199);
      if (lookahead != 0) ADVANCE(200);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(190);
      if (lookahead == '*') ADVANCE(189);
      if (lookahead == 'W') ADVANCE(180);
      if (lookahead == 'n') ADVANCE(120);
      if (lookahead == 'q') ADVANCE(149);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(223);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '-', 172,
        '.', 160,
        '/', 161,
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'x', 162,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(173);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 160,
        '/', 161,
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'x', 162,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 160,
        '/', 161,
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'x', 162,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 160,
        '/', 161,
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'x', 162,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '.', 160,
        '/', 161,
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'x', 162,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(163);
      if (lookahead == 'H') ADVANCE(216);
      if (lookahead == 'M') ADVANCE(217);
      if (lookahead == 'S') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(163);
      if (lookahead == 'S') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '.', 164,
        'c', 31,
        'g', 212,
        'k', 65,
        'l', 33,
        'o', 154,
        'p', 116,
        's', 147,
        't', 211,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ADVANCE_MAP(
        '.', 169,
        'c', 32,
        'g', 208,
        'k', 67,
        'l', 35,
        'o', 155,
        'p', 118,
        's', 148,
        't', 207,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(171);
      END_STATE();
    case 15:
      if (lookahead == '@') ADVANCE(193);
      if (lookahead == 'n') ADVANCE(196);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 16:
      if (lookahead == '@') ADVANCE(193);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 17:
      if (lookahead == 'B') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'M') ADVANCE(217);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == 'S') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(158);
      END_STATE();
    case 21:
      if (lookahead == 'W') ADVANCE(209);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(125);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead == 'm') ADVANCE(219);
      if (lookahead == 't') ADVANCE(202);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(126);
      if (lookahead == 'd') ADVANCE(219);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(138);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(87);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(136);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(140);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(144);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(129);
      if (lookahead == 't') ADVANCE(209);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(131);
      if (lookahead == 't') ADVANCE(201);
      END_STATE();
    case 33:
      if (lookahead == 'b') ADVANCE(209);
      END_STATE();
    case 34:
      if (lookahead == 'b') ADVANCE(202);
      END_STATE();
    case 35:
      if (lookahead == 'b') ADVANCE(201);
      END_STATE();
    case 36:
      ADVANCE_MAP(
        'c', 22,
        'f', 115,
        'g', 205,
        'i', 92,
        'k', 66,
        'l', 34,
        'm', 221,
        'n', 85,
        'o', 150,
        'p', 111,
        's', 141,
        't', 204,
        'y', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ADVANCE_MAP(
        'c', 31,
        'g', 212,
        'k', 65,
        'l', 33,
        'o', 154,
        'p', 116,
        's', 147,
        't', 211,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ADVANCE_MAP(
        'c', 32,
        'g', 208,
        'k', 67,
        'l', 35,
        'o', 155,
        'p', 118,
        's', 148,
        't', 207,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(74);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(209);
      END_STATE();
    case 44:
      if (lookahead == 'd') ADVANCE(219);
      END_STATE();
    case 45:
      if (lookahead == 'd') ADVANCE(202);
      END_STATE();
    case 46:
      if (lookahead == 'd') ADVANCE(183);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(201);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == 's') ADVANCE(50);
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(209);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(124);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(219);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(219);
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(202);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(179);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(201);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(185);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(186);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(178);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(123);
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 65:
      if (lookahead == 'g') ADVANCE(209);
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(202);
      if (lookahead == 'i') ADVANCE(80);
      if (lookahead == 'm') ADVANCE(219);
      END_STATE();
    case 67:
      if (lookahead == 'g') ADVANCE(201);
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 68:
      if (lookahead == 'g') ADVANCE(128);
      if (lookahead == 'm') ADVANCE(64);
      END_STATE();
    case 69:
      if (lookahead == 'g') ADVANCE(130);
      END_STATE();
    case 70:
      if (lookahead == 'g') ADVANCE(132);
      END_STATE();
    case 71:
      if (lookahead == 'h') ADVANCE(219);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(219);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(88);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(135);
      END_STATE();
    case 75:
      if (lookahead == 'i') ADVANCE(91);
      if (lookahead == 'm') ADVANCE(202);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(89);
      if (lookahead == 'm') ADVANCE(209);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(94);
      if (lookahead == 'm') ADVANCE(201);
      END_STATE();
    case 78:
      if (lookahead == 'i') ADVANCE(114);
      END_STATE();
    case 79:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 80:
      if (lookahead == 'l') ADVANCE(109);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(121);
      END_STATE();
    case 83:
      if (lookahead == 'm') ADVANCE(209);
      END_STATE();
    case 84:
      if (lookahead == 'm') ADVANCE(202);
      END_STATE();
    case 85:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 86:
      if (lookahead == 'm') ADVANCE(122);
      END_STATE();
    case 87:
      if (lookahead == 'm') ADVANCE(201);
      END_STATE();
    case 88:
      if (lookahead == 'm') ADVANCE(64);
      END_STATE();
    case 89:
      if (lookahead == 'n') ADVANCE(209);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(46);
      if (lookahead == 'x') ADVANCE(61);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(202);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(220);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 94:
      if (lookahead == 'n') ADVANCE(201);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(182);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(142);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 102:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 103:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 104:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 105:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 106:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 107:
      if (lookahead == 'n') ADVANCE(103);
      END_STATE();
    case 108:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 109:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 110:
      if (lookahead == 'o') ADVANCE(69);
      END_STATE();
    case 111:
      if (lookahead == 'o') ADVANCE(151);
      END_STATE();
    case 112:
      if (lookahead == 'o') ADVANCE(137);
      END_STATE();
    case 113:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 114:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 115:
      if (lookahead == 'o') ADVANCE(112);
      if (lookahead == 't') ADVANCE(219);
      END_STATE();
    case 116:
      if (lookahead == 'o') ADVANCE(152);
      END_STATE();
    case 117:
      if (lookahead == 'o') ADVANCE(102);
      END_STATE();
    case 118:
      if (lookahead == 'o') ADVANCE(153);
      END_STATE();
    case 119:
      if (lookahead == 'o') ADVANCE(103);
      END_STATE();
    case 120:
      if (lookahead == 'o') ADVANCE(145);
      END_STATE();
    case 121:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 122:
      if (lookahead == 'p') ADVANCE(79);
      END_STATE();
    case 123:
      if (lookahead == 'r') ADVANCE(219);
      END_STATE();
    case 124:
      if (lookahead == 'r') ADVANCE(156);
      END_STATE();
    case 125:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 126:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 127:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 128:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 129:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 130:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 131:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 132:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 133:
      if (lookahead == 's') ADVANCE(134);
      END_STATE();
    case 134:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 135:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 136:
      if (lookahead == 't') ADVANCE(209);
      END_STATE();
    case 137:
      if (lookahead == 't') ADVANCE(219);
      END_STATE();
    case 138:
      if (lookahead == 't') ADVANCE(202);
      END_STATE();
    case 139:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 140:
      if (lookahead == 't') ADVANCE(201);
      END_STATE();
    case 141:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 143:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 144:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 145:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 146:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 147:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 148:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 149:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 150:
      if (lookahead == 'u') ADVANCE(93);
      if (lookahead == 'z') ADVANCE(202);
      END_STATE();
    case 151:
      if (lookahead == 'u') ADVANCE(96);
      END_STATE();
    case 152:
      if (lookahead == 'u') ADVANCE(98);
      END_STATE();
    case 153:
      if (lookahead == 'u') ADVANCE(99);
      END_STATE();
    case 154:
      if (lookahead == 'u') ADVANCE(104);
      if (lookahead == 'z') ADVANCE(209);
      END_STATE();
    case 155:
      if (lookahead == 'u') ADVANCE(106);
      if (lookahead == 'z') ADVANCE(201);
      END_STATE();
    case 156:
      if (lookahead == 'y') ADVANCE(181);
      END_STATE();
    case 157:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(157);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 158:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 159:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 160:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 161:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(213);
      END_STATE();
    case 162:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(214);
      END_STATE();
    case 163:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 164:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 165:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(218);
      END_STATE();
    case 166:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 167:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(188);
      END_STATE();
    case 168:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 169:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 170:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(159);
      END_STATE();
    case 171:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(165);
      END_STATE();
    case 172:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(166);
      END_STATE();
    case 173:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(167);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(176);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_note);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_note);
      if (lookahead == ':') ADVANCE(187);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_W);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_ATsession);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_ATend);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_ATexercise);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_ATtemplate);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_note_COLON);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == ':') ADVANCE(187);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(198);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'd') ADVANCE(184);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(195);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'e') ADVANCE(191);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'n') ADVANCE(192);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 'o') ADVANCE(197);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead == 't') ADVANCE(194);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(aux_sym_item_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(198);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(200);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(200);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(203);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == 'o') ADVANCE(107);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '+') ADVANCE(168);
      if (lookahead == 'r') ADVANCE(206);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(105);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_weight);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(210);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_rep_scheme);
      if (lookahead == '/') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(213);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_rep_scheme);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(214);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_time_of_day);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_distance);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'e') ADVANCE(139);
      if (lookahead == 'i') ADVANCE(222);
      if (lookahead == 'm') ADVANCE(219);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_distance);
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 157},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 157},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 157},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [anon_sym_W] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_ATsession] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATexercise] = ACTIONS(1),
    [anon_sym_ATtemplate] = ACTIONS(1),
    [anon_sym_note_COLON] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_weight] = ACTIONS(1),
    [sym_rep_scheme] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_time_of_day] = ACTIONS(1),
    [sym_distance] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym__entry] = STATE(2),
    [sym_singleline_entry] = STATE(2),
    [sym_note_entry] = STATE(2),
    [sym_weigh_in_entry] = STATE(2),
    [sym_query_entry] = STATE(2),
    [sym_session_block] = STATE(2),
    [sym_exercise_block] = STATE(2),
    [sym_template_block] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_ATsession] = ACTIONS(7),
    [anon_sym_ATexercise] = ACTIONS(9),
    [anon_sym_ATtemplate] = ACTIONS(11),
    [sym_date] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_ATsession,
    ACTIONS(9), 1,
      anon_sym_ATexercise,
    ACTIONS(11), 1,
      anon_sym_ATtemplate,
    ACTIONS(13), 1,
      sym_date,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      anon_sym_LF,
      sym_comment,
    STATE(3), 9,
      sym__entry,
      sym_singleline_entry,
      sym_note_entry,
      sym_weigh_in_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [31] = 7,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_ATsession,
    ACTIONS(27), 1,
      anon_sym_ATexercise,
    ACTIONS(30), 1,
      anon_sym_ATtemplate,
    ACTIONS(33), 1,
      sym_date,
    ACTIONS(21), 2,
      anon_sym_LF,
      sym_comment,
    STATE(3), 9,
      sym__entry,
      sym_singleline_entry,
      sym_note_entry,
      sym_weigh_in_entry,
      sym_query_entry,
      sym_session_block,
      sym_exercise_block,
      sym_template_block,
      aux_sym_source_file_repeat1,
  [62] = 8,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_duration,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    STATE(17), 1,
      aux_sym_details_repeat1,
    STATE(61), 1,
      sym_details,
  [87] = 1,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [97] = 1,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [107] = 5,
    ACTIONS(52), 1,
      anon_sym_ATend,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    STATE(75), 1,
      sym_item,
    STATE(15), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [125] = 1,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [135] = 1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [145] = 1,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [155] = 1,
    ACTIONS(64), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [165] = 7,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_duration,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    STATE(17), 1,
      aux_sym_details_repeat1,
    STATE(69), 1,
      sym_details,
  [187] = 1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [197] = 1,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [207] = 5,
    ACTIONS(70), 1,
      anon_sym_ATend,
    ACTIONS(72), 1,
      anon_sym_note_COLON,
    ACTIONS(75), 1,
      aux_sym_item_token1,
    STATE(75), 1,
      sym_item,
    STATE(15), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [225] = 1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [235] = 7,
    ACTIONS(38), 1,
      sym_weight,
    ACTIONS(40), 1,
      sym_rep_scheme,
    ACTIONS(42), 1,
      sym_duration,
    ACTIONS(44), 1,
      sym_distance,
    ACTIONS(46), 1,
      sym_quoted_string,
    ACTIONS(80), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym_details_repeat1,
  [257] = 7,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(84), 1,
      sym_weight,
    ACTIONS(87), 1,
      sym_rep_scheme,
    ACTIONS(90), 1,
      sym_duration,
    ACTIONS(93), 1,
      sym_distance,
    ACTIONS(96), 1,
      sym_quoted_string,
    STATE(18), 1,
      aux_sym_details_repeat1,
  [279] = 1,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [289] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(101), 1,
      anon_sym_ATend,
    STATE(75), 1,
      sym_item,
    STATE(7), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [307] = 1,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [317] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(105), 1,
      anon_sym_ATend,
    STATE(75), 1,
      sym_item,
    STATE(23), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [335] = 5,
    ACTIONS(54), 1,
      anon_sym_note_COLON,
    ACTIONS(56), 1,
      aux_sym_item_token1,
    ACTIONS(107), 1,
      anon_sym_ATend,
    STATE(75), 1,
      sym_item,
    STATE(15), 3,
      sym_item_line,
      sym_note_line,
      aux_sym_session_block_repeat1,
  [353] = 1,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [363] = 1,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [373] = 1,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_ATsession,
      anon_sym_ATexercise,
      anon_sym_ATtemplate,
      sym_date,
  [383] = 5,
    ACTIONS(115), 1,
      anon_sym_note,
    ACTIONS(117), 1,
      anon_sym_W,
    ACTIONS(119), 1,
      anon_sym_query,
    STATE(42), 1,
      sym_flag,
    ACTIONS(121), 2,
      anon_sym_STAR,
      anon_sym_BANG,
  [400] = 1,
    ACTIONS(123), 6,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [409] = 1,
    ACTIONS(125), 6,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [418] = 1,
    ACTIONS(127), 6,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [427] = 1,
    ACTIONS(129), 6,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [436] = 1,
    ACTIONS(131), 6,
      anon_sym_LF,
      sym_weight,
      sym_rep_scheme,
      sym_duration,
      sym_distance,
      sym_quoted_string,
  [445] = 4,
    ACTIONS(133), 1,
      anon_sym_ATend,
    ACTIONS(135), 1,
      aux_sym_item_token1,
    STATE(70), 1,
      sym_identifier,
    STATE(33), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [459] = 4,
    ACTIONS(138), 1,
      anon_sym_ATend,
    ACTIONS(140), 1,
      aux_sym_item_token1,
    STATE(70), 1,
      sym_identifier,
    STATE(35), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [473] = 4,
    ACTIONS(140), 1,
      aux_sym_item_token1,
    ACTIONS(142), 1,
      anon_sym_ATend,
    STATE(70), 1,
      sym_identifier,
    STATE(33), 2,
      sym_metadata_line,
      aux_sym_exercise_block_repeat1,
  [487] = 2,
    ACTIONS(146), 1,
      anon_sym_note_COLON,
    ACTIONS(144), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [495] = 3,
    ACTIONS(148), 1,
      anon_sym_LF,
    ACTIONS(150), 1,
      sym_time_of_day,
    ACTIONS(152), 1,
      sym_quoted_string,
  [505] = 3,
    ACTIONS(154), 1,
      anon_sym_LF,
    ACTIONS(156), 1,
      aux_sym_name_token1,
    STATE(66), 1,
      sym_text_until_newline,
  [515] = 2,
    STATE(43), 1,
      sym_flag,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_BANG,
  [523] = 2,
    ACTIONS(162), 1,
      anon_sym_note_COLON,
    ACTIONS(160), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [531] = 1,
    ACTIONS(164), 2,
      anon_sym_LF,
      anon_sym_COLON,
  [536] = 2,
    ACTIONS(166), 1,
      aux_sym_item_token1,
    STATE(62), 1,
      sym_item,
  [543] = 2,
    ACTIONS(168), 1,
      aux_sym_name_token1,
    STATE(53), 1,
      sym_name,
  [550] = 1,
    ACTIONS(170), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [555] = 2,
    ACTIONS(168), 1,
      aux_sym_name_token1,
    STATE(54), 1,
      sym_name,
  [562] = 2,
    ACTIONS(172), 1,
      aux_sym_item_token1,
    STATE(80), 1,
      sym_identifier,
  [569] = 2,
    ACTIONS(174), 1,
      anon_sym_LF,
    ACTIONS(176), 1,
      sym_quoted_string,
  [576] = 1,
    ACTIONS(178), 2,
      anon_sym_ATend,
      aux_sym_item_token1,
  [581] = 1,
    ACTIONS(180), 1,
      anon_sym_LF,
  [585] = 1,
    ACTIONS(182), 1,
      anon_sym_LF,
  [589] = 1,
    ACTIONS(184), 1,
      anon_sym_LF,
  [593] = 1,
    ACTIONS(186), 1,
      anon_sym_LF,
  [597] = 1,
    ACTIONS(188), 1,
      anon_sym_LF,
  [601] = 1,
    ACTIONS(190), 1,
      anon_sym_LF,
  [605] = 1,
    ACTIONS(192), 1,
      anon_sym_LF,
  [609] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [613] = 1,
    ACTIONS(196), 1,
      anon_sym_LF,
  [617] = 1,
    ACTIONS(198), 1,
      anon_sym_LF,
  [621] = 1,
    ACTIONS(200), 1,
      sym_quoted_string,
  [625] = 1,
    ACTIONS(202), 1,
      anon_sym_COLON,
  [629] = 1,
    ACTIONS(204), 1,
      anon_sym_LF,
  [633] = 1,
    ACTIONS(206), 1,
      anon_sym_COLON,
  [637] = 1,
    ACTIONS(208), 1,
      anon_sym_LF,
  [641] = 1,
    ACTIONS(210), 1,
      sym_quoted_string,
  [645] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [649] = 1,
    ACTIONS(214), 1,
      anon_sym_LF,
  [653] = 1,
    ACTIONS(216), 1,
      anon_sym_LF,
  [657] = 1,
    ACTIONS(218), 1,
      sym_weight,
  [661] = 1,
    ACTIONS(220), 1,
      anon_sym_LF,
  [665] = 1,
    ACTIONS(222), 1,
      anon_sym_COLON,
  [669] = 1,
    ACTIONS(224), 1,
      anon_sym_LF,
  [673] = 1,
    ACTIONS(226), 1,
      sym_quoted_string,
  [677] = 1,
    ACTIONS(228), 1,
      sym_quoted_string,
  [681] = 1,
    ACTIONS(230), 1,
      anon_sym_LF,
  [685] = 1,
    ACTIONS(232), 1,
      anon_sym_COLON,
  [689] = 1,
    ACTIONS(234), 1,
      anon_sym_LF,
  [693] = 1,
    ACTIONS(236), 1,
      sym_date,
  [697] = 1,
    ACTIONS(238), 1,
      aux_sym_item_token1,
  [701] = 1,
    ACTIONS(240), 1,
      anon_sym_LF,
  [705] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [709] = 1,
    ACTIONS(238), 1,
      aux_sym_name_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 97,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 125,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 155,
  [SMALL_STATE(12)] = 165,
  [SMALL_STATE(13)] = 187,
  [SMALL_STATE(14)] = 197,
  [SMALL_STATE(15)] = 207,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 235,
  [SMALL_STATE(18)] = 257,
  [SMALL_STATE(19)] = 279,
  [SMALL_STATE(20)] = 289,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 317,
  [SMALL_STATE(23)] = 335,
  [SMALL_STATE(24)] = 353,
  [SMALL_STATE(25)] = 363,
  [SMALL_STATE(26)] = 373,
  [SMALL_STATE(27)] = 383,
  [SMALL_STATE(28)] = 400,
  [SMALL_STATE(29)] = 409,
  [SMALL_STATE(30)] = 418,
  [SMALL_STATE(31)] = 427,
  [SMALL_STATE(32)] = 436,
  [SMALL_STATE(33)] = 445,
  [SMALL_STATE(34)] = 459,
  [SMALL_STATE(35)] = 473,
  [SMALL_STATE(36)] = 487,
  [SMALL_STATE(37)] = 495,
  [SMALL_STATE(38)] = 505,
  [SMALL_STATE(39)] = 515,
  [SMALL_STATE(40)] = 523,
  [SMALL_STATE(41)] = 531,
  [SMALL_STATE(42)] = 536,
  [SMALL_STATE(43)] = 543,
  [SMALL_STATE(44)] = 550,
  [SMALL_STATE(45)] = 555,
  [SMALL_STATE(46)] = 562,
  [SMALL_STATE(47)] = 569,
  [SMALL_STATE(48)] = 576,
  [SMALL_STATE(49)] = 581,
  [SMALL_STATE(50)] = 585,
  [SMALL_STATE(51)] = 589,
  [SMALL_STATE(52)] = 593,
  [SMALL_STATE(53)] = 597,
  [SMALL_STATE(54)] = 601,
  [SMALL_STATE(55)] = 605,
  [SMALL_STATE(56)] = 609,
  [SMALL_STATE(57)] = 613,
  [SMALL_STATE(58)] = 617,
  [SMALL_STATE(59)] = 621,
  [SMALL_STATE(60)] = 625,
  [SMALL_STATE(61)] = 629,
  [SMALL_STATE(62)] = 633,
  [SMALL_STATE(63)] = 637,
  [SMALL_STATE(64)] = 641,
  [SMALL_STATE(65)] = 645,
  [SMALL_STATE(66)] = 649,
  [SMALL_STATE(67)] = 653,
  [SMALL_STATE(68)] = 657,
  [SMALL_STATE(69)] = 661,
  [SMALL_STATE(70)] = 665,
  [SMALL_STATE(71)] = 669,
  [SMALL_STATE(72)] = 673,
  [SMALL_STATE(73)] = 677,
  [SMALL_STATE(74)] = 681,
  [SMALL_STATE(75)] = 685,
  [SMALL_STATE(76)] = 689,
  [SMALL_STATE(77)] = 693,
  [SMALL_STATE(78)] = 697,
  [SMALL_STATE(79)] = 701,
  [SMALL_STATE(80)] = 705,
  [SMALL_STATE(81)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 6, 0, 3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_entry, 5, 0, 6),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_entry, 4, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 4, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 5, 0, 5),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 5, 0, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_block, 5, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 5, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_session_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 5, 0, 7),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_details, 1, 0, 13),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18), SHIFT_REPEAT(28),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18), SHIFT_REPEAT(29),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18), SHIFT_REPEAT(31),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18), SHIFT_REPEAT(30),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 2, 0, 18), SHIFT_REPEAT(32),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleline_entry, 6, 0, 17),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_block, 6, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weigh_in_entry, 6, 0, 16),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 8, 0, 21),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session_block, 9, 0, 21),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 8),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 9),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 11),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_details_repeat1, 1, 0, 12),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_exercise_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_line, 4, 0, 20),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_line, 4, 0, 20),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_line, 3, 0, 15),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_line, 3, 0, 15),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 3, 0, 14),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 4, 0, 19),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_until_newline, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
